// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (int32, error)
	GetEvent(ctx context.Context, id int32) (GetEventRow, error)
}

var _ Querier = (*Queries)(nil)
